# "[]" present the group infomation, each column means:
#[group id, group name].
#
#Each group contains children, the children present using category id,
#and the format of each child is "cat=cat_id,cat_name".
#

[1,"Adult"]
cat=1,"Adult / Mature Content"
cat=3,"Pornography"
cat=4,"Sex Education"
cat=5,"Intimate Apparel / Swimsuit"
cat=6,"Nudity"
cat=8,"Alcohol / Tobacco"
cat=9,"Illegal / Questionable"
cat=10,"Tasteless"
cat=11,"Gambling"
cat=14,"Violence / Hate / Racism"
cat=15,"Weapons"
cat=16,"Abortion"
cat=25,"Illegal Drug"
cat=26,"Marijuana"
[2,"Communications and Search"]
cat=17,"Dynamic DNS"
cat=24,"Internet Telephony"
cat=39,"Proxy Avoidance and Anonymizers"
cat=40,"Search Engines / Portals"
cat=41,"Internet Infrastructure"
cat=42,"Blogs / Web Communications"
cat=50,"Social Networking"
cat=51,"Chat / Instant Messaging"
cat=52,"Email"
cat=53,"Newsgroups / Forum"
cat=82,"Coin Miners"
cat=89,"Web Hosting"
[3,"Network Bandwidth"]
cat=23,"Internet Radio and TV"
cat=43,"Photo Searches"
cat=56,"Sharing Services"
cat=57,"Peer-to-Peer"
cat=69,"Streaming Media / MP3"
cat=70,"Ring tones/Mobile Phone Download"
cat=71,"Software Downloads"
cat=72,"Pay to Surf"
[4,"Lifestyle"]
cat=18,"Recreation / Hobbies"
cat=19,"Arts"
cat=20,"Entertainment"
cat=22,"Cult / Occult"
cat=29,"Cultural Institutions"
cat=30,"Activist Groups"
cat=33,"Games"
cat=44,"Alternative Journals"
cat=47,"Personals / Dating"
cat=54,"Religion"
cat=55,"Personal Sites"
cat=61,"Society / Lifestyle"
cat=63,"Gun Clubs / Hunting"
cat=64,"Restaurants / Food"
cat=65,"Sports"
cat=66,"Travel"
cat=68,"Humor"
cat=87,"For Kids"
[5,"Business"]
cat=21,"Business / Economy"
cat=31,"Financial Services"
cat=32,"Brokerages / Trading"
cat=45,"Job Search / Careers"
cat=58,"Shopping"
cat=59,"Auctions"
cat=60,"Real Estate"
[6,"General"]
cat=27,"Education"
cat=34,"Government / Legal"
cat=35,"Military"
cat=36,"Politics"
cat=37,"Health"
cat=38,"Computers / Internet"
cat=46,"News / Media"
cat=48,"Translators / Cached Pages"
cat=49,"Reference"
cat=67,"Vehicles"
cat=90,"Untested"
cat=96,"Miscellaneous"
[7,"Internet Security"]
cat=73,"Potentially Malicious Software"
cat=76,"Spam"
cat=86,"Made for AdSense"
cat=88,"Web Advertisements"

