# "[]" present the group infomation, each column means:
#[group id, group name].
#
#Each group contains children, the children present using category id,
#and the format of each child is "cat=cat_id,cat_name".
#

[1,"Internet Security"]
cat=02,"Illegal or Prohibited Content"
cat=28,"Insecure IoT Connections"
cat=74,"Spyware"
cat=75,"Phishing"
cat=77,"Adware"
cat=78,"Malware Accomplice"
cat=79,"Disease Vector"
cat=92,"Malicious Domain"
cat=94,"Scam"
cat=95,"Ransomware"
[2,"C&C Server"]
cat=91,"C&C Server"

